language: python
notifications:
  email:
    - phil.burger@moz.org
dist: trusty
python:
  - "3.7.1"
install:
  - pip install -r requirements.txt

# command to build and run tests
script:
  - ssh-keygen -y -f /home/travis/.ssh/id_rsa > /home/travis/.ssh/id_rsa.pub
  - cat /home/travis/.ssh/id_rsa.pub >> /home/travis/.ssh/authorized_keys
  - python setup.py test -a "-v" 
